
services:
  postgres:
    image: postgres:16
    container_name: skillhub_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stolenDev.to
      POSTGRES_DB: skillhub
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    image: skill-hub
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.production
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

volumes:
  pgdata:
    name: skillhub

